services:
  - type: web
    name: rightscripts
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TOGETHER_API_KEY
        sync: false